export const discipline = [
  { value: "matemática", label: "Matemática" },
  { value: "português", label: "Português" },
  { value: "história", label: "História" },
  { value: "geografia", label: "Geografia" },
  { value: "física", label: "Física" },
  { value: "química", label: "Química" },
  { value: "biologia", label: "Biologia" },
  { value: "inglês", label: "Inglês" },
  { value: "artes", label: "Artes" },
  { value: "educação física", label: "Educação Física" },
  { value: "filosofia", label: "Filosofia" },
  { value: "sociologia", label: "Sociologia" },
  { value: "literatura", label: "Literatura" },
  { value: "redação", label: "Redação" },
  { value: "espanhol", label: "Espanhol" },
  { value: "informática", label: "Informática" },
  { value: "programação", label: "Programação" },
  { value: "estatística", label: "Estatística" },
  { value: "economia", label: "Economia" },
  { value: "administração", label: "Administração" },
  { value: "direito", label: "Direito" },
  { value: "psicologia", label: "Psicologia" },
  { value: "ciências sociais", label: "Ciências Sociais" },
  { value: "teatro", label: "Teatro" },
  { value: "música", label: "Música" },
  { value: "desenho técnico", label: "Desenho Técnico" },
  { value: "engenharia civil", label: "Engenharia Civil" },
  { value: "medicina", label: "Medicina" },
  { value: "enfermagem", label: "Enfermagem" },
  { value: "arquitetura", label: "Arquitetura" },
  { value: "design gráfico", label: "Design Gráfico" },
  { value: "marketing", label: "Marketing" },
  { value: "finanças", label: "Finanças" },
  { value: "contabilidade", label: "Contabilidade" },
  { value: "recursos humanos", label: "Recursos Humanos" },
  { value: "logística", label: "Logística" },
  { value: "comunicação social", label: "Comunicação Social" },
  { value: "jornalismo", label: "Jornalismo" },
  { value: "publicidade e propaganda", label: "Publicidade e Propaganda" },
  { value: "relações internacionais", label: "Relações Internacionais" },
  { value: "antropologia", label: "Antropologia" },
  { value: "astronomia", label: "Astronomia" },
  { value: "botânica", label: "Botânica" },
  { value: "zoologia", label: "Zoologia" },
  { value: "genética", label: "Genética" },
  { value: "ecologia", label: "Ecologia" },
  { value: "geologia", label: "Geologia" },
  { value: "meteorologia", label: "Meteorologia" },
  { value: "oceanografia", label: "Oceanografia" },
  { value: "paleontologia", label: "Paleontologia" },
  { value: "farmacologia", label: "Farmacologia" },
  { value: "nutrição", label: "Nutrição" },
  { value: "gastronomia", label: "Gastronomia" },
  { value: "agronomia", label: "Agronomia" },
  { value: "veterinária", label: "Veterinária" },
  { value: "dentística", label: "Dentística" },
  { value: "fisioterapia", label: "Fisioterapia" },
  { value: "fonoaudiologia", label: "Fonoaudiologia" },
  { value: "terapia ocupacional", label: "Terapia Ocupacional" },
  { value: "radiologia", label: "Radiologia" },
  { value: "biomedicina", label: "Biomedicina" },
  { value: "engenharia elétrica", label: "Engenharia Elétrica" },
  { value: "engenharia mecânica", label: "Engenharia Mecânica" },
  { value: "engenharia química", label: "Engenharia Química" },
  { value: "engenharia de software", label: "Engenharia de Software" },
  { value: "engenharia de produção", label: "Engenharia de Produção" },
  { value: "engenharia ambiental", label: "Engenharia Ambiental" },
  { value: "engenharia aeronáutica", label: "Engenharia Aeronáutica" },
  { value: "engenharia de alimentos", label: "Engenharia de Alimentos" },
  { value: "engenharia de materiais", label: "Engenharia de Materiais" },
  { value: "engenharia de petróleo", label: "Engenharia de Petróleo" },
  { value: "engenharia nuclear", label: "Engenharia Nuclear" },
  { value: "engenharia biomédica", label: "Engenharia Biomédica" },
  {
    value: "engenharia de controle e automação",
    label: "Engenharia de Controle e Automação",
  },
  { value: "engenharia de energia", label: "Engenharia de Energia" },
  { value: "engenharia têxtil", label: "Engenharia Têxtil" },
  { value: "engenharia de transportes", label: "Engenharia de Transportes" },
  { value: "engenharia de minas", label: "Engenharia de Minas" },
  { value: "engenharia de agrimensura", label: "Engenharia de Agrimensura" },
  {
    value: "engenharia de segurança do trabalho",
    label: "Engenharia de Segurança do Trabalho",
  },
  {
    value: "outra",
    label: "Outra",
  },
];
