import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Baloo_Tamma_2 } from "next/font/google";
import { dark } from "@clerk/themes";
import { ptBR } from "@clerk/localizations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const baloo = Baloo_Tamma_2({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
      localization={ptBR}
    >
      <html>
        <body className={`antialiased ${baloo.className}`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
